### ISSUE TITLE
more features may needed.

### ISSUE THREAD

**Issue by LeuisKen** [alkin/vue-react#3]
I have the same idea like you, I want to write a vue-react-loader, that can import react component like vue component using webpack, for a more vue native way to use react components, but there is some problems.

We map the props and events from vue to react, but there is some react components like this.

https://ant.design/components/table/#Column

Here is a table component of react, it has a render method let you custom how your column render. How to write this render method in "parent" vue component and pass it to the target "child" react component that wrapped by a vue component.(Since jsx is just js object, there is some "dirty" way (like write compiled jsx) to solve this, maybe here is a better way?)

And think about vue "slot" and react "props.children", I have no idea about how to implement this [Form](https://ant.design/components/form/) component in our way to use React component in vue.

Please forgive my poor English, did I make myself clear?

**Comment by LeuisKen** [comment]
And by the way current solution can not use the react vdom diff I think?

**Comment by alkin** [comment]
Thanks for being interested in this project =) I am not very experienced with React development, so i would definitely appreciate some help.

As i understand, JSX is just a wrapper to React.CreateComponent ([ref](https://reactjs.org/docs/jsx-in-depth.html)) which in turn returns a ReactNode.

Any of the improvements you commented would require the ability to inject Vue components into React components.

Implementing the default Vue slot shouldnt be difficult. `React.props.children` is a ReactElement and `Vue.$slots` is an array of VNodes. I am not sure how React uses VNodes. I will to do some research on how we could map $slots into children.

React doesnt support named slots natively, but i found this package [react-slot](https://www.npmjs.com/package/react-slot) that adds this functionality, If we manage to get the default slot working, i believe we can somehow implement named slots with this package.

As for the Form component, if we manage to get the default slot working and register all the React subcomponents as Vue components it should work.

**Comment by alkin** [comment]
I will be able to work on this issue later this week. As soon i have some ideas i let you know.

**Comment by alkin** [comment]
Please check my last commit. I created the `props.children` based on the `$slots.default` array of VNodes.

I tested with the Ant Design Framework and it worked for simple slots. My code still doesn't convert Vue Components to React's children, so we can't still use the Form component you proposed.

```vuejs
<Button>
   Testing<br>
   <strong>bold</strong>
</Button>
```

The above code works.

**Comment by alkin** [comment]
I will be implementing full slot support in the coming weeks. Closed for now.
